tonitealive:
  filestoreservice:
    rootFolder: production

stormpath:
  client:
    cacheManager:
      enabled: false

  authorized:
    group:
      admin: https://api.stormpath.com/v1/groups/44oU56OXxsDQHDHTqqyogS
      user: https://api.stormpath.com/v1/groups/5q9Hkh3lN221LYraSLx6XY
      promoter: https://api.stormpath.com/v1/groups/6A9pheRSMbDLWRvLoB98JE

spring:
  http:
    converters:
      preferred-json-mapper: jackson

---

spring:
  profiles:
    active: dev

tonitealive:
  filestoreservice:
    rootFolder: development

stormpath:
  application:
    href: https://api.stormpath.com/v1/applications/5l8ew1CAGoh1Um0mr7gAQY

  authorized:
    group:
      admin: https://api.stormpath.com/v1/groups/2mJuLDpWc7EPcTsdk3YKnd
      user: https://api.stormpath.com/v1/groups/ciqlYQj0D9WMDU6OGLBT1
      promoter: https://api.stormpath.com/v1/groups/1PqTvjjylp01wvqiNZGif7