stormpath:
  client:
    cacheManager:
      enabled: false

  authorized:
    group:
      admin: https://api.stormpath.com/v1/groups/44oU56OXxsDQHDHTqqyogS
      user: https://api.stormpath.com/v1/groups/5q9Hkh3lN221LYraSLx6XY
      promoter: https://api.stormpath.com/v1/groups/6A9pheRSMbDLWRvLoB98JE

