# Debug profile configuration
stormpath:
  application:
    href: https://api.stormpath.com/v1/applications/5l8ew1CAGoh1Um0mr7gAQY

  authorized:
    group:
      admin: https://api.stormpath.com/v1/groups/2mJuLDpWc7EPcTsdk3YKnd
      user: https://api.stormpath.com/v1/groups/ciqlYQj0D9WMDU6OGLBT1
      promoter: https://api.stormpath.com/v1/groups/1PqTvjjylp01wvqiNZGif7

logging:
  level:
    com.tonitealive.server: DEBUG

